### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by pranav1812** [sudiptadas2000k/Inhouse-Project-Human-Pose-Detection#1]
Hi Maintainer, 
    Thanks for uploading this. Do you have any decent modifications on the top of this project. I need it for a college assignment on pose detection and recognition. I'm pretty new to ML stuff. Any help/suggestion will be appreciated 

Thanks

**Comment by sudiptadas2000k** [comment]
Yep, you can use different TensorFlow Model for this project, Apart from that This project Is sufficient as per your college project requirement
Hope it Help
